HotColdSplitting: check that target supports cold calling convention
Before tagging a function with coldcc make sure the target supports cold calling
convention. Without this patch HotColdSplitting pass fails on aarch64 with:

  fatal error: error in backend: Unsupported calling convention.

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@341838 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit d126aab2ef8cd48165e03c4d7bcb7abf0a56fc4f)

apple-llvm-split-commit: bd2b77502f6f079f329d2b512c4bdde8b7d43401
apple-llvm-split-dir: llvm/