Removed unused variable [NFC]
The compiler warned:
../tools/clang/lib/StaticAnalyzer/Core/RetainSummaryManager.cpp:329:19: error: unused variable 'MD' [-Werror,-Wunused-variable]
  if (const auto *MD = dyn_cast<CXXMethodDecl>(FD)) {
                  ^
1 error generated.

git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@340524 91177308-0d34-0410-b5e6-96231b3b80d8
apple-llvm-split-commit: 87357b84454213368fe539ca6f07ba51a2dd189f
apple-llvm-split-dir: clang/